name: Waka Readme

on:
  schedule:
    # Runs at 5am UTC / 4PM AEDT
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: FAXES/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_UPDATED_DATE: False
          COMMIT_MESSAGE: "Updated readme statistics"
          COMMIT_BY_ME: True
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          SHOW_TIMEZONE: False
          SHOW_SHORT_INFO_HIRE: False
          SHOW_SHORT_INFO_STORAGE: True
          SHOW_SHORT_INFO_CONTRIBUTIONS: True
          SHOW_SHORT_INFO_PUBLIC: True
          SHOW_SHORT_INFO_PRIVATE: True
