name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches:    
      - source
    paths:
      - 'README.md'
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Calculate statistics and push it onto main branch 📈
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_LOC_CHART: "True" 
          COMMIT_SINGLE: "True"
          PULL_BRANCH_NAME: source
          PUSH_BRANCH_NAME: main
          SYMBOL_VERSION: 2
